name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
        env:
          CI: true

      - run: npx prettier --check .

      - run: npm run lint

      - run: npm run test:coverage

      - run: npm run build